"""Vault layout (grounded-vault convention) and its two root files, index.md and log.md."""

from dataclasses import dataclass
from pathlib import Path

from ckm.fsio import write_text
from ckm.manifest import ManifestRow


@dataclass(frozen=True)
class Vault:
    root: Path

    @property
    def raw(self) -> Path:  # immutable source snapshots; never edited by hand or agent
        return self.root / "raw"

    @property
    def wiki(self) -> Path:  # the knowledge modules
        return self.root / "wiki"

    @property
    def archive(self) -> Path:  # modules whose page left the export; moved, never deleted
        return self.root / "archive"

    @property
    def manifest(self) -> Path:
        return self.root / "manifest.csv"

    @property
    def index(self) -> Path:
        return self.root / "index.md"

    @property
    def log(self) -> Path:
        return self.root / "log.md"

    def write_index(self, rows: dict[str, ManifestRow], *, dry_run: bool = False) -> bool:
        current = [r for r in rows.values() if r.status in ("extracted", "curated")]
        current.sort(key=lambda r: r.title.lower())
        lines = [
            "# Vault index",
            "",
            "Generated by `ckm extract`; do not edit. One row per current module.",
            "",
            "| Module | Status | Page id | Source |",
            "|---|---|---|---|",
        ]
        for r in current:
            title = r.title.replace("|", "\\|")
            lines.append(
                f"| [{title}]({r.module_path}) | {r.status} | {r.page_id} | raw/{r.page_id}.html |"
            )
        held = sorted(
            (r for r in rows.values() if r.status in ("blocked", "archived")),
            key=lambda r: r.page_id,
        )
        if held:
            lines += [
                "",
                "## Not current",
                "",
                "| Page id | Title | Status | Note |",
                "|---|---|---|---|",
            ]
            lines += [
                f"| {r.page_id} | {r.title.replace('|', '\\|')} | {r.status} | {r.note} |"
                for r in held
            ]
        return write_text(self.index, "\n".join(lines) + "\n", dry_run=dry_run)

    def append_log(self, lines: list[str], *, dry_run: bool = False) -> None:
        if not lines or dry_run:
            return
        existing = self.log.read_text(encoding="utf-8") if self.log.is_file() else "# Vault log\n\n"
        write_text(self.log, existing + "".join(f"{line}\n" for line in lines))
